### ISSUE TITLE
无法查询

### ISSUE THREAD

**Issue by wlyangcug** [shell909090/influx-proxy#102]
hello，请教下，本地部署了influx-proxy、两个influxdb节点，双写没问题，但是查询不可以，禁止查询 query forbidden。

![image](https://user-images.githubusercontent.com/16377372/85253950-c7966000-b491-11ea-89f1-7d6255befdaf.png)

![image](https://user-images.githubusercontent.com/16377372/85254002-e4329800-b491-11ea-9955-e1248fd7b1a1.png)

查询语句为：select * from w where time > now()

**Comment by shell909090** [comment]
你改错代码了。
如你图示，在cluster.go#L383，你禁用了query检查。但是你没有禁用下面的err检查，也没有查看上面的代码。上面是为了influx-proxy自己的执行器预留的接口，只有当err的时候（也就是influx-proxy自己的执行器无法处理命令的时候）才往下走。因此，在383行，err默认不为nil。在CheckQuery生效的时候，err的值会被覆盖，因此没有逻辑问题。你注释了383行，又没有对上面进行处理，因此百分百会出现错误。
请在上一个段落结束处增加err = nil。并且注释CheckQuery对应的错误处理部分。
