### ISSUE TITLE
启动参数-config

### ISSUE THREAD

**Issue by guideyong** [shell909090/influx-proxy#105]

**Comment by guideyong** [comment]
启动参数里-config的作用是什么，指定配置文件吗？还有就是能否通过文件配置的方式替代redis？感觉redis有点多余。

**Comment by shell909090** [comment]
配置文件的话，对于集群部署不好管理。我本来计划是用etcd取代redis的。结果后来...

**Comment by guideyong** [comment]
明白了，这块我通过文件的方式重写了此段逻辑，可以替代redis，关于配置文件有一点不明白的就是MaxRowLimit这个具体是指对什么数量限制？interval的说明上说当超出MaxRowLimit设置值后会等待一秒写入，经过测试interval好像对于连续写入的间隔有影响，配置成一秒时我在一秒内发起多次写入也只会写入一条。不知道我的理解是否正确，对此有点疑惑

**Comment by shell909090** [comment]
https://github.com/shell909090/influx-proxy/blob/master/backend/backends.go#L130
超过这个数值后会启动一次flush，不管到没到1s。
