### ISSUE TITLE
插入内容带\\无法插入

### ISSUE THREAD

**Issue by guideyong** [shell909090/influx-proxy#106]
今天测试一组数据发现如果数据带\\符号时会报错，具体报错如下，请帮忙确认下为什么会禁止\\插入
2020/07/30 19:32:56.912012 influxql.go:338: scan quote error: wrong quote
2020/07/30 19:32:56.912096 proxy.go:325: invalid format, drop data: see n cbOracle_cbOracle_sessionStat,host=10.20.42.221,monitorKey=f7387810099a4e808776488abce522a5 cpu_used=1.0,createtime=1596108738543i,event="SQL*Net message from client",logical_reads=117651.0,machine="WORKGROUP\\WIN-VDKUNI2B4QI",osuser="Administrator",physical_reads=0.0,program="procmaintran.exe",sid=1183.0,spid=18928.0,status="INACTIVE",used_memory=1030.14,username="TRADE" 1596108739033000019

**Comment by chengshiwen** [comment]
这个问题是 [chengshiwen/influx-proxy](https://github.com/chengshiwen/influx-proxy) 的一处bug：https://github.com/chengshiwen/influx-proxy/blob/master/backend/proxy.go#L325
目前已经在 dev 分支修复，相关 commit 为：3ec7115
相关修改记录：https://github.com/chengshiwen/influx-proxy/commit/3ec71158cd45dd0ca706a0c17a89767e45b47550

@guideyong

**Comment by shell909090** [comment]
多谢

**Comment by guideyong** [comment]
@chengshiwen 好的，我自己去掉了相关代码后重新编译解决了。多谢
