### ISSUE TITLE
请问，实现动态获取redis中注册的配置信息，需要操作什么？

### ISSUE THREAD

**Issue by nmonz** [shell909090/influx-proxy#108]
请问，实现动态获取redis中注册的配置信息，需要操作什么？

**Comment by shell909090** [comment]
当然是redis

**Comment by nmonz** [comment]
主要是操作那个*.go，是不是应该轮询几秒加载一次 还是说实时监测当config.py有变化马上加载可获取




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shell909090/influx-proxy"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 下午4:43
收件人:&nbsp;"shell909090/influx-proxy"<influx-proxy@noreply.github.com&gt;;
抄送:&nbsp;"李峰"<646584614@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [shell909090/influx-proxy] 请问，实现动态获取redis中注册的配置信息，需要操作什么？ (#108)





 
当然是redis

**Comment by shell909090** [comment]
哦，你说这个。
规划中，应该把redis干掉换用etcd...
