### ISSUE TITLE
使用recovery恢复circle数据时报错

### ISSUE THREAD

**Issue by guideyong** [shell909090/influx-proxy#109]
@chengshiwen 
使用recovery恢复circle数据时报错，具体报错内容如下，能帮忙看下具体什么原因吗
![image](https://user-images.githubusercontent.com/29939997/94138849-4b9a2280-fe9b-11ea-95bf-a2be91cc05e8.png)

**Comment by chengshiwen** [comment]
@guideyong 已经修复，原因是recovery时，json反序列化会导致大整数（像13位时间戳）被转换成小数，格式和精度都会出问题，已经在 [chengshiwen/influx-proxy 最新 dev 分支 ca0a54e](https://github.com/chengshiwen/influx-proxy/commit/ca0a54ee00c44005385b349eee96d7478f18fab9) 修复，感谢！
