### ISSUE TITLE
influxDB版本选择

### ISSUE THREAD

**Issue by zhangyang1995** [shell909090/influx-proxy#110]
请问集现在inlfuxDB已经发展到2.0版本  influx-proxy最高可以支持哪个版本？

**Comment by chengshiwen** [comment]
@zhangyang1995  最高支持 v1.8，目前 v2.0 还没正式发布，并且 api 存在不兼容，尚未适配

**Comment by zhangyang1995** [comment]
> @zhangyang1995 最高支持 v1.8，目前 v2.0 还没正式发布，并且 api 存在不兼容，尚未适配

1.8.3可以吗 谢谢大佬

**Comment by chengshiwen** [comment]
可以的，v1.x.y 都是兼容的

**Comment by zhangyang1995** [comment]
谢谢大佬
