### ISSUE TITLE
query forbidden

### ISSUE THREAD

**Issue by zhangyang1995** [shell909090/influx-proxy#113]
config.py

BACKENDS = {
    'local': {
        'url': 'http://192.168.84.136:8086',
        'db': 'demo',
        'zone':'local', 
        'interval': 1000,
        'timeout': 10000, 
        'timeoutquery':600000, 
        'maxrowlimit':10000,  
        'checkinterval':1000, 
        'rewriteinterval':10000,
    },
    'local2': {
        'url': 'http://192.168.84.137:8086',
        'db': 'demo',
        'interval': 200,
    },
}

# measurement:[backends keys], the key must be in the BACKENDS
# data with the measurement will write to the backends
KEYMAPS = {
    'disk_': ['local'],
    'temperature': ['local2'],
    '_default_': ['local','local2']
}

进行http api查询的时候，count（*）可以查出数据 但是*就查不出数据

请求
http://192.168.84.134:6666/query?q=select count(*) from disk_free where time = 1603691279971905323
&db=test
结果：
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "disk_free",
                    "columns": [
                        "time",
                        "count_value"
                    ],
                    "values": [
                        [
                            "2020-10-26T05:47:59.971905323Z",
                            1
                        ]
                    ]
                }
            ]
        }
    ]
}
请求：
http://192.168.84.134:6666/query?q=select *  from disk_free where time = 1603691279971905323
&db=test
结果：
query forbidden

**Comment by zhangyang1995** [comment]
根据https://github.com/shell909090/influx-proxy/blob/master/backend/commands.go得知*被禁止使用
后面看尝试修改 * 改为字段 可以查询到

**Comment by chengshiwen** [comment]
@zhangyang1995 这个版本里通过正则表达式支持和限制部分sql语句，[https://github.com/shell909090/influx-proxy/blob/master/backend/commands.go](https://github.com/shell909090/influx-proxy/blob/master/backend/commands.go) 有设置

**Comment by zhangyang1995** [comment]
> @zhangyang1995 这个版本里通过正则表达式支持和限制部分sql语句，https://github.com/shell909090/influx-proxy/blob/master/backend/commands.go 有设置





嗯这点我看了 后期有需要会改一下  在请问一下 是否支持策略插入
1m是我定义的一个策略

name    duration shardGroupDuration replicaN default
autogen 0s       168h0m0s           1        false
1m      1h0m0s   1h0m0s             1        true

 insert into "1m" disk_free,hostname=server01 value=442.0 
如果是上面的语句在每一个db实例上是可以插入的，切换到proxy就不行了
我现在是把1m定义为默认策略插入语句是这样
 insert into  disk_free,hostname=server01 value=442.0
proxy下的2个db实例是都可以获取到数据的

在请问一下如果java想使用proxy 直接就用官方的jdbc 连接我们config.py里面的node就可以了吗？ 比如ip:6666端口

**Comment by zhangyang1995** [comment]
> > @zhangyang1995 这个版本里通过正则表达式支持和限制部分sql语句，https://github.com/shell909090/influx-proxy/blob/master/backend/commands.go 有设置
> 
> 嗯这点我看了 后期有需要会改一下 在请问一下 是否支持策略插入
> 1m是我定义的一个策略
> 
> name duration shardGroupDuration replicaN default
> autogen 0s 168h0m0s 1 false
> 1m 1h0m0s 1h0m0s 1 true
> 
> insert into "1m" disk_free,hostname=server01 value=442.0
> 如果是上面的语句在每一个db实例上是可以插入的，切换到proxy就不行了
> 我现在是把1m定义为默认策略插入语句是这样
> insert into disk_free,hostname=server01 value=442.0
> proxy下的2个db实例是都可以插进去数据的
> 
>

**Comment by chengshiwen** [comment]
@zhangyang1995 这个版本的 proxy 还不支持 retention policy 的设置，即 influxdb cli、influxdb shell、influxdb http 都不支持
补充：这个版本的 proxy 的 http /write 接口 也不支持 precision 和 rp 参数
我近期在规划添支持 rp，其中 precision 已经在 [https://github.com/chengshiwen/influx-proxy](https://github.com/chengshiwen/influx-proxy) 支持
