### ISSUE TITLE
横向扩展怎么

### ISSUE THREAD

**Issue by wang1219** [shell909090/influx-proxy#15]
Hi @shell909090 我看所有的influxdb节点都在这块写死了
{
BACKENDS = {
    'local': {
        'url': 'http://localhost:8086', 
        'db': 'test', 
        'zone':'local', 
        'interval': 1000,
        'timeout': 10000, 
        'timeoutquery':600000, 
        'maxrowlimit':10000,  
        'checkinterval':1000, 
        'rewriteinterval':10000,
    },
    'local2': {
        'url': 'http://influxdb-test:8086',
        'db': 'test2',
        'interval': 200,
    },
}
那要是想横向扩展的话要怎么做呢？

**Comment by pingliu** [comment]
严格来说这个proxy不支持横向扩展，是根据measurement分发的到对应的backends.
如果一台机器一个measurement扛不住的话，说明你的机器配置低，需要用更高配置的机器。

**Comment by shell909090** [comment]
其实并不是不支持横向扩展，而是扩展粒度要以measurement为单位。即，你只能为新的measurement分配新机器，或者将原本在同一台机器上的多个measurement拆分到多个机器上。目前本proxy不支持将一个measurement分发到多个机器上。
