### ISSUE TITLE
一点疑惑

### ISSUE THREAD

**Issue by rfyiamcool** [shell909090/influx-proxy#19]
简单看了下代码，逻辑是根据后端 influxdb的measurement 选择入库，还没做 shard分片的逻辑，这个其实可以有的。    

@shell909090   我记得  七牛 应该早已经实现了自己的influxdb proxy...    你也有参与吧...

**Comment by lwhile** [comment]
@rfyiamcool 七牛实现的influxdb proxy开源了吗?

**Comment by pingliu** [comment]
@rfyiamcool shard分片只会增加复杂性，目前这个场景已经够用，除非一个influxdb扛不住一个measurement的量。

**Comment by wlcwfwyt** [comment]
@pingliu ,那要一个fluxdb的节点挂了，其他节点能有挂掉节点的measurement可用吗，如果没有还不是实例级别的高可用

**Comment by shell909090** [comment]
@rfyiamcool 不好意思，七牛的这个项目我没参与，而且我记得还没开源。
shard分片的逻辑其实并不算难，原本预计是下半年做掉的，不过因为某些因素就没做下去。

**Comment by shell909090** [comment]
@lwhile 我记得是没有，目前这部分在七牛大数据那里有个业务，您可以直接使用这部分业务。

**Comment by shell909090** [comment]
@wlcwfwyt 可以。你可以把一个measurement写到多个后端节点上去。我们实践是写到两个机房里（跨机房延迟写入），因此整个系统是跨机房高可用的。

**Comment by zwfha** [comment]
@shell909090 你好， 看实现目前应该是以垂直分片为主要实现，可以实现按业务/IP等类似纬度做水平分片么？？多谢 。
