### ISSUE TITLE
通过influx-proxy使用query时报错：query forbidden

### ISSUE THREAD

**Issue by isser** [shell909090/influx-proxy#27]
安装配置好influx-proxy之后，write方法已经没有问题了，可以同时写入两台influxdb，但是query方法一直不行，报错query forbidden，没有更多的信息，麻烦帮忙看一下是什么问题，谢谢！

query方法：
```
curl -G 'http://172.16.6.104:6666/query' --data-urlencode "db=telegraf" --data-urlencode "epoch=s" --data-urlencode "q=SELECT value FROM cpu_load_short WHERE region='us-west'"
```

核心配置如下：
```
BACKENDS = {
    'local': {
        'url': 'http://172.16.6.103:8086', 
        'db': 'telegraf', 
        'zone':'l1', 
        'interval': 1000,
        'timeout': 10000, 
        'timeoutquery':600000, 
        'maxrowlimit':10000,  
        'checkinterval':1000, 
        'rewriteinterval':10000
    },
    'local2': {
        'url': 'http://172.16.6.104:8086',
        'db': 'telegraf',
        'zone':'l1',
        'interval': 1000
    },
}

KEYMAPS = {
    'cpu': ['local','local2']
}

NODES = {
    'l1': { 
        'listenaddr': ':6666',
        'db': 'telegraf',
        'zone': 'l1',
        'interval':10,
        'idletimeout':10,
        'writetracing':1,
        'querytracing':1,
    }
}
```

**Comment by pingliu** [comment]
文档中说明了，查询必须带时间纬度

**Comment by isser** [comment]
您好！，带上时间也是一样的错误

```
curl -G 'http://172.16.6.104:6666/query' --data-urlencode "db=telegraf" --data-urlencode "epoch=s" --data-urlencode "q=SELECT value FROM cpu_load_short WHERE region='us-west' and time > now() - 10m" 
```

**Comment by pingliu** [comment]
![image](https://user-images.githubusercontent.com/6415493/30540455-daf12f20-9ca9-11e7-8e38-8ad8bfa23ceb.png)
我这边查询ok

**Comment by pingliu** [comment]
请问influxdb是什么版本

**Comment by isser** [comment]
Connected to http://localhost:8086 version 1.2.2
InfluxDB shell version: 1.2.2

**Comment by pingliu** [comment]
我这边试了1.2.2的都没有问题，你自己检查哪里有问题吧

**Comment by isser** [comment]
如果我的配置您看了没问题的话，能否将编译好的可执行包（您试了没问题的）发我一下，我看看是否是编译出了问题？

**Comment by huzhuo** [comment]
我在InfluxDB 1.4版本上也出现这个问题了，下面是日志：
2018/01/05 17:37:12.157844 cluster.go:460: new measurement: influxdb.cluster
2018/01/05 17:37:22.157781 cluster.go:460: new measurement: influxdb.cluster
2018/01/05 17:37:32.157778 cluster.go:460: new measurement: influxdb.cluster
2018/01/05 17:37:37.663261 http.go:86: query error: query forbidden,the query is select cpu_idle from d_host_cpu where plat='SCP' and clus='TESTSCP' and host='eb6075',the client is [::1]:52276
2018/01/05 17:37:42.157886 cluster.go:460: new measurement: influxdb.cluster

**Comment by shell909090** [comment]
query forbidden并不是因为您的后端出问题，而是您的查询语句并不符合一定的范式。在我们这，由于客户端查询语句我们并不可控，不符合范式的查询语句可能会直接将数据库打挂。所以我们禁用了部分语句。您列出的语句里，where后面并没有time，因此不能通过查询。但是上面那句select后面带有时间，应该能够通过。

**Comment by shell909090** [comment]
@huzhuo 目前我的推论是，可能是由于q后面没有大小写处理，大写的where被过滤了。这是一个bug。如果方便，您是否能改为小写复现一下问题，我确认后好着手修理。

**Comment by RoryLiuwenxuan** [comment]
@shell909090 
您好,遇到了相同的问题,使用influx-proxy可以向两个数据库写数据,但是查询的时候报错query forbidden,原来是用influx为0.13.0,换成1.2版本还是同样的问题.
所有查询使用的关键字都换为了小写,配置同isser相同.

`curl -G 'http://localhost:6666/query' --data-urlencode "db=test" --data-urlencode "epoch=s" --data-urlencode "q=select * from cpu where region='us-west' and time > now() - 10m"`

有什么好的建议吗?谢谢

@isser 
您解决了这个问题吗?方不方便指导一下.

**Comment by shell909090** [comment]
@RoryLiuwenxuan @isser 
可以注释这行，及其下面部分。这样所有语句都不会被拦截。
https://github.com/shell909090/influx-proxy/blob/master/backend/cluster.go#L378
如果想要了解具体哪个部分被拦截，可以截取CheckQuery函数直接调用。这样比较易于调试。

**Comment by RoryLiuwenxuan** [comment]
@shell909090 注释这一行代码有效。问题解决了。谢谢。

**Comment by MasonYangD** [comment]
shell
还是不行啊，我注释了，依然还是那个禁止查询，调试了，感觉哪里有缓存似的，改的东西都没成功。
需要重新编译吗

**Comment by shell909090** [comment]
...当然...

**Comment by MasonYangD** [comment]
shell 你好
我用$GOPATH/bin/influxdb-proxy -redis localhost:6379 重新编译了，但是发现我修改的代码根本没有起作用，这是什么情况？
谢谢

**Comment by shell909090** [comment]
@MasonYangD 你贴的指令不是重编译的指令，是不是贴错了？
