### ISSUE TITLE
源码文件有完成下载，但是没法完成编译。

### ISSUE THREAD

**Issue by tycjlee** [shell909090/influx-proxy#28]
查看了源码文件有完成下载，但是没法完成编译。
[root@rhel6 bin]# go get -u github.com/shell909090/influx-proxy
package github.com/shell909090/influx-proxy: no buildable Go source files in /mygo/src/github.com/shell909090/influx-proxy

**Comment by ipfans** [comment]
Please try this: ```go get -u github.com/shell909090/influx-proxy/service```

**Comment by pingliu** [comment]
go版本请用1.8以上

**Comment by tycjlee** [comment]
使用：go get -u github.com/shell909090/influx-proxy/service不会报错，但是存在一个问题
我已经手工安装和启动了redis，但是安装程序一直卡在redis的下载安装进程，如何跳过redis的安装？

 root       4495   4307  0 08:43 pts/1 git clone https://gopkg.in/redis.v5 /open-falcon/Paasapplications/mygo/src/gopkg.in/redis.v5
root       4497   4495  0 08:43 pts/1  git-remote-https https://gopkg.in/redis.v5 https://gopkg.in/redis.v5

**Comment by liluo1990** [comment]
为什么用go get -u github.com/shell909090/influx-proxy/service 而不用 go get -u github.com/shell909090/influx-proxy/ 或者 go get -u github.com/shell909090/influx-proxy/monitor呢

**Comment by shell909090** [comment]
@tycjlee 如果你下载和安装redis的驱动库正确的话，golang是不会自动帮你下载这个库的。你是不是下载到自定目录，而不是系统指定目录？

**Comment by shell909090** [comment]
@liluo1990 因为这样的话main函数就要写在github.com/shell909090/influx-proxy/里了。
