### ISSUE TITLE
[doubts] Some doubts on how to work with this promising tool

### ISSUE THREAD

**Issue by toni-moreno** [shell909090/influx-proxy#29]
HI @shell909090  I'm looking for a influx proxy/write cache/write filter system tool, And I've found your influx-proxy.

I've doubts on how it works and why. ( Perhaps I could help you to add some new features if you like it)

1) why are you using redis as a config repository? if seems  easier to work with a toml file like influx-proxy does?
2) do you use redis also as metric cache in case of remote infludb services are down?
3) does influx-proxy detects configuration changes automatically and reconfigure itself online?
4) does influx-proxy support  a "db to destination" keymap as it already supports "measurement to destination" ?

Thank you very much

**Comment by shell909090** [comment]
1. Cause I planned to change to etcd, but not finished yet.
2. No, just config. influxdb cache are way too much then redis can do.
3. No, you had to call url to reload it. However, etcd will give you that ability.
4. Not yet. That's a good point. But mostly we ust one and just one db for all users.
