### ISSUE TITLE
水平分片需求

### ISSUE THREAD

**Issue by zwfha** [shell909090/influx-proxy#31]
你好，请问可实现“水平分片”功能么？ 比如，按IP地址/区域/网段/业务 等自定义的规则分别存储到多个influxdb.
目前看到的应该是实现了measument层面的“垂直切分”吧？ 但，如果一个中心内要监控的内容太多。同一measuments的数据量也会出现过大的情况。。不知贵司是如何避免此情况的啊？

**Comment by shell909090** [comment]
避免不了。
水平分片功能本来预期是去年下半年开始做的，后来因为种种理由，项目终止。。。
