### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by lsllcm66** [shell909090/influx-proxy#32]
我再使用下列命令时出现下列错误，请问readme中的命令是否可以使用。谢谢。

[root@vm1 influx-proxy]# go get -u github.com/shell909090/influx-proxy 

# cd /root/go/src/github.com/shell909090/influx-proxy 

; git pull --ff-only
error:  while accessing https://github.com/shell909090/influx-proxy/info/refs 

fatal: HTTP request failed
package github.com/shell909090/influx-proxy 

: exit status 1

**Comment by shell909090** [comment]
我看到README中的指令并不是
go get -u github.com/shell909090/influx-proxy
而是
go get -u github.com/shell909090/influx-proxy/service
而且修改时间在17年。

您是不是再看一下？
