### ISSUE TITLE
是否支持动态扩展influxDB

### ISSUE THREAD

**Issue by yangminglis** [shell909090/influx-proxy#38]
是否支持添加和减少influxDB

**Comment by guodidi** [comment]
减少/增加influxdb措施
1. 向redis推送最新的数据信息
2. 向influxdb-proxy发送/reload信号

但是增加influxdb只会有增量数据

**Comment by shell909090** [comment]
我们是通过人肉操作来解决这个问题的。因为influxdb本身没有自动迁移工具，所以这个事情并不好做。
1. 首先在influxdb列表中增加新机器，并设定新增机器的WriteOnly。
2. 等待并经过0点。
3. 将一台旧机器的昨日以前数据导入到新机器。（具体参考influxdb迁移，基本就是拷贝数据）
4. 将新机器切换为ReadWrite。
