### ISSUE TITLE
如果一个后段influxdb实例挂掉，这部分历史数据会丢吗

### ISSUE THREAD

**Issue by lycclsltt** [shell909090/influx-proxy#43]
如果一个后段influxdb实例挂掉，这部分历史数据会丢吗

**Comment by shell909090** [comment]
yes，当然会。所以这就是为什么我们一般推荐每个measurement写两个backend的缘故。
我们的实战里，两个backend位于不同机房，所以等于顺便把多机房多活一起做了。
