### ISSUE TITLE
后面挂的两个influxdb实例，每个实例的数据是相同的吗？还是分片的？

### ISSUE THREAD

**Issue by lycclsltt** [shell909090/influx-proxy#44]
后面挂的两个influxdb实例，每个实例的数据是相同的吗？还是分片的？

**Comment by shell909090** [comment]
influx-proxy的基本数据结构是，多个backend，然后每个measurement自行决定写入哪个backend。所以理论上每个backend所拥有的数据可以不一致。但是在实践中这么做比较复杂。我们目前都是用prefix功能，给同类的一组需求分配对称的两台backend，放在两个zone里面。
另外，influx-proxy没有数据分片功能。
