### ISSUE TITLE
安装过程，运行python config.py报错

### ISSUE THREAD

**Issue by kanon7** [shell909090/influx-proxy#47]
按照安装文件，已经安装了redis和influxdb，
运行到python config.py时，报错。
Traceback (most recent call last):   
File "config.py", line 13, in <module>     
import redis ImportError: No module named redis
知道原因，就不知道怎么处理。你的操作步骤写的略简单，水平有限，在慢慢消化。希望这个问题抽空处理下。

**Comment by shell909090** [comment]
OK。我们没写这个是因为我们认为这算是比较简单的一步。你出现这个错误是因为没有装redis的python包。Python需要这个包来操作redis，把所有配置写入到redis里去。
