### ISSUE TITLE
（1）redis是cluster模式的是不是没有兼容？（2）influxdb的password怎么传

### ISSUE THREAD

**Issue by frontdog** [shell909090/influx-proxy#48]

**Comment by shell909090** [comment]
1. 其实我们压根没有设计兼容redis cluster mode。redis本身都属于work through。我们的目标其实是主用etcd，次之才是redis。你可以注意到有个load config的api？etcd就不需要这个，而且自动保证一致性。
2. 我们也没设计要给influxdb加password，反倒是对外要不要搞password一直有争议。因为proxy后的influxdb可以认为是proxy独享(dedicated)的。这种情况下，用password并没有任何意义。反正就一个用户，一个源IP。反而是proxy本身可以被多个用户分享。但是在这种情况下，我们就需要介入用户认证和鉴权。鉴权系统怎么搞一直没有统一意见。

**Comment by shell909090** [comment]
@pingliu 刘老师有没有想法搞一把etcd？
