### ISSUE TITLE
query的机器选择的是哪台机器

### ISSUE THREAD

**Issue by frontdog** [shell909090/influx-proxy#49]
两台influxdb机器：A和B。
所有数据都同时存入两台机器，例如KEYMAPS的配置为：
```
KEYMAPS = {
    temperature: ["A", "B"]
}
```
写入temperature的时候会同时写入两台机器，那么query的时候现在的表现是去第一个backend也就是A里面拿数据，即使这次query报错
这样是对的吗？

**Comment by shell909090** [comment]
write的时候是两台都写，query就复杂的多。首先去除掉write_only的，只写的不参与query。然后优先选择同一个zone的，一般就是同机房。如果都没有，再任意选择。至于query是否成功，在选择时并不知道。

**Comment by frontdog** [comment]
> write的时候是两台都写，query就复杂的多。首先去除掉write_only的，只写的不参与query。然后优先选择同一个zone的，一般就是同机房。如果都没有，再任意选择。至于query是否成功，在选择时并不知道。

那这样万一有台机器挂了，会有机制去过滤吗？不然的话如果一旦是选中的那台挂掉了，就无法query了

**Comment by shell909090** [comment]
> > write的时候是两台都写，query就复杂的多。首先去除掉write_only的，只写的不参与query。然后优先选择同一个zone的，一般就是同机房。如果都没有，再任意选择。至于query是否成功，在选择时并不知道。
> 
> 那这样万一有台机器挂了，会有机制去过滤吗？不然的话如果一旦是选中的那台挂掉了，就无法query了

这个会有。如果query返回了错误(而不是查询返回错误)，那么proxy会尽量在同级别内重试。不行就降级重试。具体哪些错误会被query返回，可以查看这个函数。

https://github.com/shell909090/influx-proxy/blob/master/backend/http.go#L134
