### ISSUE TITLE
go get -u github.com/shell909090/influx-proxy/service  失败！！！

### ISSUE THREAD

**Issue by StefTang** [shell909090/influx-proxy#51]
[root@localhost src]# go get -u github.com/shell909090/influx-proxy/service

package gopkg.in/redis.v5: unrecognized import path "gopkg.in/redis.v5" (https fetch: Get https://gopkg.in/redis.v5?go-get=1: dial tcp 35.196.143.184:443: getsockopt: connection refused)

package gopkg.in/natefinch/lumberjack.v2: unrecognized import path "gopkg.in/natefinch/lumberjack.v2" (https fetch: Get https://gopkg.in/natefinch/lumberjack.v2?go-get=1: dial tcp 35.196.143.184:443: getsockopt: connection refused)

求问下该怎么解决。

**Comment by shell909090** [comment]
翻墙。当然是翻墙。

**Comment by StefTang** [comment]
发现问题了，实际上有点无奈。
因为公司网络本来就是翻墙的，平时就可以Google的，然后我看了上面报出"https://gopkg.in/redis.v5"无法访问。试了下公司外网确实是访问不到，但用手机的移动网络反而可以。
那很可能是公司网络设置了一些“IP黑白名单”所导致的。。。

**Comment by shell909090** [comment]
跪了。
