### ISSUE TITLE
influx-proxy 高可用问题

### ISSUE THREAD

**Issue by yangzan66** [shell909090/influx-proxy#54]
nginx   ------  nginx
   			  |
     influxProxy-1    influxProxy-2
                         |
  influxDB01      influxDB02   influxDB03

   influx-proxy高可用环境下，如果有多个influx-proxy服务器，需要把所有的influxdb-proxy服务器都写在config.py里的NOEDS这吗？ 是使用IP;6666来区分吗？多个influx-proxy使用的config.py文件完全一样？  还是第一个influx-proxy的config.py里写l1, 第二个influx-proxy里写l2?
       一个node是一个influx-proxy，NODES里的db是什么作用呢？BACKENDS里已经指定了后端influxdb的db， BACKENDS里有多个不同的db，例如示例中的test和test2，那这个NODES里的db怎么设呢？
       这些influx-proxy都挂在nginx负载均衡器上，这个DEFAULT_NODE该怎么设置？
       nginx建议用哪种负载均衡模式（调度算法）？
谢谢

NODES = {
    'l1': { 
        'listenaddr': '192.168.1.31:6666',
        'db': 'test',
        'zone': 'local',
        'interval':10,
        'idletimeout':10,
        'writetracing':0,
        'querytracing':0,
}
    'l2': { 
        'listenaddr': '192.168.1.32:6666',
        'db': 'test',
        'zone': 'local',
        'interval':10,
        'idletimeout':10,
        'writetracing':0,
        'querytracing':0,
    }

}

   the influxdb default cluster node 
DEFAULT_NODE = {
    'listenaddr': ':6666'
}

**Comment by shell909090** [comment]
config.py其实并不重要。你要是有别的手段操纵redis，一样可以用。
多个proxy实例彼此用nodename来指定，启动时可以传入。load设定的时候，先load default node名字对应的那个node的所有信息，再load启动时指定的node名字对应的那个node的所有信息。
如果你的所有nodes配置均相同(尤其注意IP相同，例如0.0.0.0)，那么你直接设定一个default就结了。如果有不同，用nodename指定配置来重载。
每个实例都会验证你的db是否正确。如果你设定了db，当客户端的db指定不正确时就会拒绝服务。这个和backend有没有dbname，叫什么，没有关系。
nginx负载均衡算法不重要。只要你的机器没有挂，都没事。

**Comment by yangzan66** [comment]
谢谢解释
&nbsp&nbsp我有2个influx-proxy服务器，一个IP是192.168.1.31，一个是192.168.1.32。
 一台服务器上只跑一个influx-proxy实例。
&nbsp&nbsp每个proxy都把这些配置信息写入自己服务器上的redis里，那这2个proxy之间就没什么关系了吧？他们之间同步信息吗？ 
&nbsp&nbsp你说的“如果你设定了db，当客户端的db指定不正确时就会拒绝服务” 这里的客户端是指的redis吗？如果我指定了db，这个db如果不存在，redis会自动创建吧？

配置文件里说明有“this config will cover default_node config”NODES的配置会覆盖default_node的配置。是指的是只有在启动influx-proxy时用-node string指定node名字，才会覆盖default_node吧？ 如果不使用-node string参数，那么他就是使用的default_node里的配置，NODES里的配置不会覆盖掉default_node的配置吧？

我理解现在有2种配置方法，这两种方法都对吗？
方法1：
2台influx-proxy服务器使用相同的配置文件，只配置NODES部分，default_node部分不配了。 如下，
2台influx-proxy的db名字一不一样没关系吧？因为他们是本机redis里的db吧？
在192.168.1.31上启动proxy时，用-node指定使用NODES里的哪个配置
# $GOPATH/bin/influxdb-proxy -node **l1** -redis localhost:6379
在192.168.1.32上启动proxy时，# $GOPATH/bin/influxdb-proxy -node **l2** -redis localhost:6379

NODES = {
    'l1': { 
        'listenaddr': '192.168.1.31:6666',
        'db': 'test',
        'zone': 'local',
        'interval':10,
        'idletimeout':10,
        'writetracing':0,
        'querytracing':0,
}
    'l2': { 
        'listenaddr': '192.168.1.32:6666',
        'db': 'test',
        'zone': 'local',
        'interval':10,
        'idletimeout':10,
        'writetracing':0,
        'querytracing':0,
    }
}
DEFAULT_NODE = {
    
}


方法2：
2台influx-proxy服务器也使用相同的配置文件。不配置NODES了，只配置DEFAULT_NODE，ip是0.0.0.0， 启动influx-proxy时，它默认使用DEFAULT_NODE的配置
NODES = {
   
}

DEFAULT_NODE = {
        'listenaddr': '0.0.0.0:6666',
        'db': 'test',
        'zone': 'local',
        'interval':10,
        'idletimeout':10,
        'writetracing':0,
        'querytracing':0,
}
[root@influxdbProxy-1 ~]# $GOPATH/bin/influxdb-proxy --h
 -node string
        node name (default "l1")
他这里写的默认使用命令'l1'的NODE的配置， 如果不配置NODES，只配置DEFAULT_NODE的话，有隐患吗？

**Comment by yangzan66** [comment]
redis里只存储了config.py里的这些配置执行，还有其他作用吗？

执行config.py时会先把redis里的信息清空， 其实如果有多个influxProxy，因为他们使用的config.py是相同的，所以只要在一个influxProxy服务器上执行一遍python config.py就行了吧？不需要每个influxProxy节点上都执行python config.py吧？

如果measurement写到influxdb01和influxdb02里， influxdb01挂掉5小时（influxdb02一直正常），等influxdb01起来后，他能自动把丢失的这5小时的数据恢复回来吗？

**Comment by yangzan66** [comment]
我用测试程序写入的数据量很小，如果influxdb01挂掉几分钟，他能恢复数据。
如果数据量大的话，他能恢复多大或多长时间内的数据？
这个数据恢复的原理是什么？ 和influxdbProxy或influxdb的内存大小或redis有关系吗？
谢谢

**Comment by shell909090** [comment]
1. 你用什么工具写入redis都行，我们用config.py也就是图方便。确实不用每个节点上都跑config.py。
2. 当无法写入的时候，会将数据缓存在硬盘上。等恢复之后补充写入，然后删除文件。至于缓存量，要看硬盘什么时候被写满。写满之前都没问题。但是这也导致长时间断开后，刚启动时该实例很慢。建议这种情况把这个实例直接切换为只写，隔几个小时再去看他。

**Comment by yangzan66** [comment]
关于redis的作用，能不能再给些解释？ 多谢
我看redis只是存储了config.py里的配置信息，  还有其他作用吗？
redis有必要用高可用redis集群吗？还是单点redis就可以?
如果redis挂了，如果influxProxy已经起来了，他对influxProxy有影响吗？
influxProxy应该在启动时就把redis里的内容都读到自己这来了吧。
redis有过期时间，数据过期数据都丢失了，这个...
我手上没有redis集群，要求其他部门申请，最小要16G的6节点集群，如果只存储一些配置信息，太浪费了，也申请不下来。
谢谢

**Comment by shell909090** [comment]
没别的作用，就是图方便。其实redis是过渡方案，etcd才是最终目标。
没必要用HA集群，如果redis挂了，充其量就是不能重启proxy，不能修改配置。我想你redis挂了不忙着修，先改监控配置，也有点怪吧。

**Comment by shell909090** [comment]
写入时如果不指定时间戳，那就是按照实际写进去的时间计算。而服务关闭的时候并不是写入完成，而是proxy帮你缓存了。这么讲能理解么？

**Comment by yangzan66** [comment]
这个明白了，influxdb再次启动后，数据恢复时  的时间戳是proxy把缓存的数据写入到influxdb的时间。
可我测试如果不指定时间戳，即使influxdb一直正常，也会丢数据。 2个influxdb里的数据时一样的 
#!/usr/bin/python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division,\
    print_function, unicode_literals
import time
import requests
from datetime import datetime


BASEURL = 'http://influxProxy.service.ycidcm5:6666'

def once(value,tem):

    s = '''cpu,host=server1,region=uswest value=%s
temperature,machine=unit2,type=assembly internal=32,external=%s
temperature,machine=unit1430,type=assembly internal=22,external=130'''%(value,tem)

    resp = requests.post(
        BASEURL+'/write', params={'db': 'yzdb'}, data=s)
    print(resp.status_code)

def main():
    tem=0
    value=0
    while True:
        once(value,tem)
        tem+=1
        value+=1
        time.sleep(0.5)

if __name__ == '__main__':
    main()


influxdb里的数据：最末尾的数字应该是自增1，但丢失了， 如果每秒写入1个数据或更慢，那么数据不丢失
> select * from cpu
name: cpu
time                           host    region value
----                           ----    ------ -----
2018-11-28T09:48:57.368152439Z server1 uswest 0
2018-11-28T09:48:57.87565486Z  server1 uswest 2
2018-11-28T09:48:58.889150236Z server1 uswest 3
2018-11-28T09:48:59.394721147Z server1 uswest 4
2018-11-28T09:48:59.902637235Z server1 uswest 6
2018-11-28T09:49:00.915948483Z server1 uswest 8
2018-11-28T09:49:01.929430959Z server1 uswest 10
2018-11-28T09:49:02.943567444Z server1 uswest 11

**Comment by shell909090** [comment]
那个，你知道influxdb对同一个时间戳的数据相互覆盖吧。如果你在恢复时大量写入，他们的时间戳就一样了。结果就...

**Comment by shell909090** [comment]
另外，influxdb-proxy的运作特性会缓存数据。这是当然，前面写过来20条数据一个报文，这个报文需要写到后面10个服务器。直接写会使得调用量放大10倍。目前的缓存算法会按照特定频率和大小缓存，满了会写出，时间到了也会自动刷出。可无论哪种都是批量写入。这同样也会触发我们刚刚说的那个问题。

**Comment by shell909090** [comment]
所以简单来说。influxdb-proxy必须配合时间戳使用，除非你的数据提交间隔远远大于proxy刷写间隔。

**Comment by yangzan66** [comment]
再请教个问题， 我们不同的业务用不同的数据库，如果有多个数据库，该怎么配置config.py文件啊？

**Comment by shell909090** [comment]
那你每个数据库的size都不会特别大吧。每个instance单独启动一个influx就好了，不用proxy。

**Comment by shell909090** [comment]
1. 你可以每个数据库配一个独立的instance，没有HA。
2. 需要HA的话每个数据库配置一个或一对proxy实例。后端怎么摆放就随意了。
3. 最好是proxy监听一个端口，然后根据数据库名区分不同配置。但是这个要改配置结构。

**Comment by yangzan66** [comment]
第3种方法， “要改配置结构”  是指的改config.py配置信息吗？ 这个该怎么改啊

**Comment by yangzan66** [comment]
那我现在最好的办法就是后端的influxdb 不变，每个influxdb里有db1，db2，db3..多个数据库，然后在influxdbProxy服务器上 起多个influxProxy进程，进程1后端对应db1， 进程2对应db2，进程3对应db3 。 是这样吧?                                 但这样我还有个疑虑，启动influxProxy进程1时，config1.py里的配置写入了redis， 但启动influxProxy进程2时，config2.py的配置又写入了同一个redis，这样不就把前面的配置覆盖了吗？

**Comment by shell909090** [comment]
每个proxy一套redis。
说白了，influxdb-proxy就没为这种情况做设计。

**Comment by yangzan66** [comment]
你们的不同业务都写到一个数据库里了吗？ 通过measurement来区分？  但用grafana展示的时候，数据源指定的是数据库啊， 你们在grafana里在整个库里过滤信息吗？

**Comment by shell909090** [comment]
proxy的核心就是根据measurement区分不同数据库啊。grafana那边展示的时候，配置一个数据源。然后你的influxql语言是一定会指定查询某个measurement的。这样就不用管理A指标在A数据库这类的问题了。

**Comment by huyujie** [comment]
@shell909090 这个数据的存储是根据measurement来分片的吗，要是proxy后面的influxdb有部分挂了，是不是那部分数据就丢了?

**Comment by shell909090** [comment]
对同一个measurement可以配置多个influxdb。配多个influx的情况下，单个db失效的时候不影响查询。写入db的时候也会做失败缓存，该db上线的时候会接收重写信息。因此正常情况下不会感受到backend失效。
