### ISSUE TITLE
没外网怎么安装influxProxy？

### ISSUE THREAD

**Issue by yangzan66** [shell909090/influx-proxy#57]
有个环境没外网，怎么安装influxProxy？
有源码编译之类的方法吗？
或者可以把有外网环境下安装好的influxProxy 直接复制一些文件过来使用吗？  需要复制哪些文件啊？

谢谢

**Comment by shell909090** [comment]
你把项目编译好了，直接复制可执行文件进去执行就行。

**Comment by yangzan66** [comment]
多谢，搭好了

**Comment by yangzan66** [comment]
多谢，搭好了
