### ISSUE TITLE
database not exists异常

### ISSUE THREAD

**Issue by mliu111477** [shell909090/influx-proxy#63]
proxy配置（部署在10.1.201.201中）：
BACKENDS = {
    'local': {
        'url': 'http://10.1.201.201:8086',
        'db': 'pard',
        'zone':'local',
        'interval': 1000,
        'timeout': 10000,
        'timeoutquery':600000,
        'maxrowlimit':10000,
        'checkinterval':1000,
        'rewriteinterval':10000,
    },
    'local2': {
        'url': 'http://10.1.201.202:8086',
        'db': 'pard',
        'interval': 200,
    },
}

KEYMAPS = {
    'cpu': ['local'],
    'temperature': ['local2'],
    '_default_': ['local']
}

在local主机中：
show databases;
name: databases
name
_internal
aTimeSeries
pard

在终端执行：
curl -G 'http://10.1.201.201:6666/query?pretty=true' --data-urlencode "db=pard" --data-urlencode "q=SELECT idle FROM cpu"
提示：
database not exist.

**Comment by shell909090** [comment]
这句提示来自这里：
https://github.com/shell909090/influx-proxy/blob/master/service/http.go#L78

原因是db=pard和你在node config中指定的名称不一致。
