### ISSUE TITLE
influx的性能指标

### ISSUE THREAD

**Issue by frontdog** [shell909090/influx-proxy#68]
想请教一下，对于influx的性能情况，贵公司是怎么去衡量的，谢谢

**Comment by frontdog** [comment]
不知道方不方便给个邮箱，有时想请教influxdb的问题。

**Comment by shell909090** [comment]
同名gmail邮箱。
没有衡量，我们大致测量过，在使用正确的情况下，几个选项，例如prometheus/influx的性能都是常数差，不到倍数差。而且这类问题并没有总体成本更低的选项。使用不正确的话，总是要教育使用者把使用做正确的。
那好像也没啥说的，选一个，配够资源就行了。
