### ISSUE TITLE
关于BACKENDS的疑问

### ISSUE THREAD

**Issue by aqqbjlgu** [shell909090/influx-proxy#71]
你好，如果我有两个BACKENDS，并将KEYMAPS配成：'cpu': ['local1','local2'], 是不是向两个BACKENDS都写数据？两个BACKENDS的数据是一模一样的？相当于做了个备份？

**Comment by shell909090** [comment]
Yes.
但是有点区别。如果两个backends的zone不一致，查询将首先被打到最近(一致)的一个zone。这其实是异地备份。

**Comment by aqqbjlgu** [comment]
嗯嗯，谢谢回答，如果两个BACKENDS的保存策略不同会有影响么？

**Comment by shell909090** [comment]
proxy的目标就是转发。其余都是influx上执行的事。如果两个influx配置不同导致查询结果有差异，在zone切换的时候会引起问题。所以建议不要这么干。
