### ISSUE TITLE
启动influx-proxy的时候日志打印：read meta error: EOF 为什么？

### ISSUE THREAD

**Issue by nmonz** [shell909090/influx-proxy#74]
2019/04/28 16:21:44.288413 file.go:208: read meta error: EOF
2019/04/28 16:21:44.288660 file.go:208: read meta error: EOF

**Comment by shell909090** [comment]
字面上看，是有meta文件但是没有内容。如果没经历过rewrite过程，这个提示应该在启动时出现一次，因为meta里面确实是没内容。如果有过rewrite过程，应该就完全不提示。
你是重复出现么？

**Comment by nmonz** [comment]
你好，是每次重启的时候日志都有这样提示，但是写数据和查数据都没问题。

**Comment by shell909090** [comment]
那没关系，仅仅是提示而已。只要不要重启后持续出现就行。
