### ISSUE TITLE
influxdb-proxy多个库使用

### ISSUE THREAD

**Issue by nmonz** [shell909090/influx-proxy#75]
目的是不同节点配置不同库。目前我准备部署二个节点一个mydb的库，一个test的库，但是在测试过程中，提示其中一个库不存在，只能正常使用一个库。请问这个高可用可以配置多个库吗？提示问题如下：
us-west value=1.11 1434255562000040512'    
HTTP/1.1 404 Not Found
X-Influxdb-Version: 1.1
Date: Tue, 30 Apr 2019 03:03:30 GMT
Content-Length: 19
Content-Type: text/plain; charset=utf-8

database not exist.

我的配置文件如下：
BACKENDS = {
    'local': {
        'url': 'http://kf-app73:8086',
        'db': 'test',
        'zone':'local',
        'interval': 1000,
        'timeout': 10000,
        'timeoutquery':600000,
        'maxrowlimit':10000,
        'checkinterval':1000,
        'rewriteinterval':10000,
    },
    'local2': {
        'url': 'http://kf-app76:8086',
        'db': 'mydb',
        'interval': 200,
        'timeout': 10000,
        'timeoutquery':600000,
        'maxrowlimit':10000,
        'checkinterval':1000,
        'rewriteinterval':10000,
    },
}
KEYMAPS = {
    'cpu': ['local','local2'],
    'temperature': ['local2','local'],
    '_default_': ['local','local2']
}
NODES = {
    'l1': {
        'listenaddr': ':6666',
        'db': 'test',
        'zone': 'local',
        'interval':10,
        'idletimeout':10,
        'writetracing':0,
        'querytracing':0,
    },
    'l2': {
        'listenaddr': ':6666',
        'db': 'mydb',
        'zone': 'local2',
        'interval':10,
        'idletimeout':10,
        'writetracing':0,
        'querytracing':0,
    }
}

# the influxdb default cluster node 
DEFAULT_NODE = {
    'listenaddr': ':6666'
}

def main():
    optlist, args = getopt.getopt('d:hH:p:', sys.argv[1:])
    optdict = dict(optlist)
    if '-h' in optdict:
        print(main.__doc__)
        return

    client = redis.StrictRedis(
        host=optdict.get('-H', 'localhost'),
        port=int(optdict.get('-p', '6379')),
        db=int(optdict.get('-d', '0')))

    cleanups(client, ['nodes', 'b:*', 'm:*', 'n:*'])

    write_config(client, DEFAULT_NODE, "nodes")
    write_configs(client, BACKENDS, 'b:')
    write_configs(client, NODES, 'n:')

**Comment by shell909090** [comment]
我完全没看懂您要干嘛，但是两个node分别叫不同的database name是会出事的。

**Comment by nmonz** [comment]
我的意思是否可以配置多个节点不同的database，然后写入的时候可以将不同的数据写进不同节点的database里？查询的时候也可以查询不同的database？

**Comment by shell909090** [comment]
我还是没太搞明白，但是我觉得您要的东西应该是这个。
https://github.com/influxdata/influxdb-relay

**Comment by nmonz** [comment]
比如我在config.py中配置了一个local、一个local2。这两个local配置的是不同的主机和database。lacal配置的是mydb库，local2配置的是test的库。然后我要既能写入local的mydb库，也要能写local2的test库中。也能通过proxy查询到local中的mydb库的数据，也能查询到local2的test的数据。

**Comment by nmonz** [comment]
这个高可用应该是按照measurements为单位来进行分片存储的吧！但是我配置了后，没按照配置的进行分片存储。什么原因呢？

**Comment by shell909090** [comment]
哦。我觉得你是不是误解了proxy的意图。proxy是将一个db的多个measurement分散到多个db上。您这是多个db。我建议您直接用nginx来解决这个问题。
db的指定是一定会写在url里的，您可以用nginx的regex规则来选择合适的backend，也可以配置多个upstream。
influx-proxy之所以没这么做，是因为同一个db的不同measurement是写在记录里的，而不是url里。所以一定要做分组重组和influxql分析。

**Comment by shell909090** [comment]
对measurements分片是对的，但是proxy自身认为自己工作在特定的数据库名字上。例如，如果您后端有backend1和backend2，对应的数据库名叫db1和db2。您的node指定的数据库名叫db3。那么您需要以db3来查询proxy，proxy会将您的查询发送到db1和db2上去。
