### ISSUE TITLE
$GOPATH/bin/influxdb-proxy -redis localhost:6379启动不了

### ISSUE THREAD

**Issue by changRJ917** [shell909090/influx-proxy#78]

**Comment by changRJ917** [comment]
没有任何的输出，是怎么回事
config.py配置文件为
BACKENDS = {
    'local': {
        #'url': 'http://localhost:8086',
        'url': 'influxdb01:8086',
        'db': 'test',
        'zone':'local',
        'interval': 1000,
        'timeout': 10000,
        'timeoutquery':600000,
        'maxrowlimit':10000,
        'checkinterval':1000,
        'rewriteinterval':10000,
    },
    'local2': {
        #'url': 'http://influxdb-test:8086',
        'url': 'influxdb02:8086',
        'db': 'test2',
        'interval': 200,
    },
}

**Comment by shell909090** [comment]
config.py的数据汇入redis了么？

**Comment by changRJ917** [comment]
> config.py的数据汇入redis了么？

谢谢大佬回复，启动已经实现，通过go build -o bin/influx-proxy github.com/shell909090/influx-proxy/service
go test -v github.com/shell909090/influx-proxy/backend重新编译测试了一下，
但现在发现，$GOPATH/bin/influxdb-proxy -redis localhost:6379可以启动完成，但是怎么查看influxdb集群部署成功呢，有什么方式呢，可否指点一下

**Comment by changRJ917** [comment]
> config.py的数据汇入redis了么？

还有，您能否帮忙看下我的配置文件修改的是否有问题呢

**Comment by shell909090** [comment]
你用influx自带的cli，像正常使用influx那样用就行。不要去查看有多少个db，有什么measurement。这些查询语句都没实现。但是一般的插入和查询都是OK的。

**Comment by changRJ917** [comment]
> 你用influx自带的cli，像正常使用influx那样用就行。不要去查看有多少个db，有什么measurement。这些查询语句都没实现。但是一般的插入和查询都是OK的。

大佬，怎么样查看proxy实现的效果呢

**Comment by shell909090** [comment]
这个你必须配至少两个backend。将两个measurement分配到两个backend上。写数据。查询proxy的时候都能访问。分别查询的时候数据分开存在两个backend上。
