### ISSUE TITLE
一个数据库能正确写入,另外一个写不进去,报database not exist.错误

### ISSUE THREAD

**Issue by www6223166** [shell909090/influx-proxy#80]
配置和您的python.py脚本完全一样,只是把Locahost换成了两个IP,一个写入正常,另外一个始终无法写入,数据库确实已经建立好了,求指教,是哪里出的问题...
BACKENDS = {
    'local': {
        'url': 'http://172.16.5.17:8086', 
        'db': 'test', 
        'zone':'local', 
        'interval': 1000,
        'timeout': 10000, 
        'timeoutquery':600000, 
        'maxrowlimit':10000,  
        'checkinterval':1000, 
        'rewriteinterval':10000,
    },
    'local2': {
        'url': 'http://172.16.4.108:8086',
        'db': 'test2',
        'interval': 200,
    },
}
KEYMAPS = {
    'cpu': ['local'],
    'temperature': ['local2'],
    '_default_': ['local']
}
NODES = {
    'l1': { 
        'listenaddr': ':6666',
        'db': 'test',
        'zone': 'local',
        'interval':10,
        'idletimeout':10,
        'writetracing':0,
        'querytracing':0,
    }
}
DEFAULT_NODE = {
    'listenaddr': ':6666'
}

**Comment by www6223166** [comment]
@shell909090 大神,求指教,这个问题已经困扰了我一天多了,我仔细研究了配置文件,感觉并没有写错什么东西,但是第二个数据库就是写不进去数据,第一个正常,第二个报database not ,求指教

**Comment by www6223166** [comment]
您这个日志是写在什么地方的,我现在完全没有头绪,不知道怎么查,哪里出错了

**Comment by www6223166** [comment]
发现了一个很奇怪的问题,使用HTTP API的方式可以正确写入,使用java代码的方式写入,始终只能写入到一个数据库中,另外一个提示database not exist

**Comment by shell909090** [comment]
为啥我刚看到问题，问题就关了...

**Comment by www6223166** [comment]
因为我已经解决了o(∩_∩)o ,
顺带问一个问题,写入的measurement名称,一定要以cpu开头吗

**Comment by MasonYangD** [comment]
那你倒是说下，这是什么问题啊，我也遇到了

**Comment by www6223166** [comment]
1：更换连接数据库的Java代码，改用原生的方式连接
2：KEYMAPS要正确配置，key表示表名必须以什么开头，value是你要写入的数据库实例id，具体再BACKENDS里配置，想写入两个就配置两个,例如 'default': ['local','local2']，示例给的并不好，所以会让第一次使用的人一头雾水

**Comment by shell909090** [comment]
@www6223166 能给一个你觉得比较合适的example么？

**Comment by www6223166** [comment]
'_default_': ['local'],把第51行改为 '_default_':['local','local2'],这样大家按照你给的配置就能直接实现双写啦o(∩_∩)o

**Comment by shell909090** [comment]
OK. Implemented in dev.
