### ISSUE TITLE
new measurement: influxdb.cluster

### ISSUE THREAD

**Issue by qq50520271** [shell909090/influx-proxy#83]
influx版本用的是version: "1.7.6" 启动后一直提示new measurement: influxdb.cluster 这是什么原因，6666端口无法正常通信
019/06/24 21:00:14.652121 file.go:208: read meta error: EOF
2019/06/24 21:00:14.653119 config.go:196: 3 measurements loaded from redis.
2019/06/24 21:00:14.654116 cluster.go:264: local2 use a backend not exists
2019/06/24 21:00:14.654116 http.go:29: http database: test
2019/06/24 21:00:14.654116 main.go:108: http service start.:6666
2019/06/24 21:00:24.657111 cluster.go:465: new measurement: influxdb.cluster
2019/06/24 21:00:34.653594 cluster.go:465: new measurement: influxdb.cluster
2019/06/24 21:00:44.652824 cluster.go:465: new measurement: influxdb.cluster
2019/06/24 21:00:54.655601 cluster.go:465: new measurement: influxdb.cluster

**Comment by shell909090** [comment]
new measurement的提示来自这里。
https://github.com/shell909090/influx-proxy/blob/master/backend/cluster.go#L465
原因为你的measurement映射到哪个backend并没有定义。
在我们的场景中，所有measurement都应该预先定义好，并由SRE review。所以不应该存在new measurement的情况。
