### ISSUE TITLE
配置后无法使用 database not exist

### ISSUE THREAD

**Issue by Laruto** [shell909090/influx-proxy#88]
您好，我按照您的步骤配置了config.py 然后成功运行，但是proxy提示database not exist
以下是我的配置信息，和报错信息
BACKENDS = {
    'local': {
        'url': 'http://localhost:8086', 
        'db': 'NOAA_water_database', 
        'zone': 'local', 
        'interval': 1000,
        'timeout': 10000, 
        'timeoutquery':600000, 
        'maxrowlimit':10000,  
        'checkinterval':1000, 
        'rewriteinterval':10000,
    },
    'local2': {
        'url': 'http://localhost:8087',
        'db': 'NOAA_water_database',
        'interval': 200,
    },
}
KEYMAPS = {
    'h2o_feet': ['local'],
    'h2o_temperature': ['local2'],
    '_default_': ['local']
}
NODES = {
    'l1': { 
        'listenaddr': ':6666',
        'db': 'NOAA_water_database',
        'zone': 'local',
        'interval':10,
        'idletimeout':10,
        'writetracing':0,
        'querytracing':0,
    }
}
![image](https://user-images.githubusercontent.com/19355223/63678456-dd130d00-c821-11e9-96d2-bfafbec07cc8.png)
![image](https://user-images.githubusercontent.com/19355223/63678524-f5832780-c821-11e9-9753-094d7fc1215e.png)

**Comment by shell909090** [comment]
你的查询代码呢？把原始请求打出来，看看是否指定了db=NOAA_water_database

**Comment by Laruto** [comment]
解决了，是我的查询语句不规范。不能使用*，查询必须指定时间

**Comment by shell909090** [comment]
应该不是这个原因。”database not exist“这个提示只会出现在请求中未指定db参数的情况下。和查询语句没什么关系。如果是查询语句被禁止，提示应当是”query forbidden“。后者可以通过调整下面的文件取消限制。dev版中已经默认取消限制。
https://github.com/shell909090/influx-proxy/blob/master/backend/commands.go
