### ISSUE TITLE
采用zk实现influxdb的高可用负载均衡，是否可行

### ISSUE THREAD

**Issue by nmonz** [shell909090/influx-proxy#92]

**Comment by shell909090** [comment]
zk? zookeeper? zookeeper没有HA或LB的功能啊。
influxdb-proxy的HA或LB方案和正常webservice没什么区别。你可以用nginx/haproxy+heartbeat的方案，也可以用LVS或者SLB的方案。proxy自身没有数据，是没关系的。

**Comment by nmonz** [comment]
@shell909090 说的不准确 应该是inflxudb-proxy的高可用和负载，这样的话也就不用keeplived了。而且我感觉更稳定。

**Comment by nmonz** [comment]
@shell909090  而且nginx本身也没高可用，如果nginx掉了也就不能写入、查询数据了吧！！

**Comment by shell909090** [comment]
所以nginx前面要加heartbeat啊。

**Comment by nmonz** [comment]
@shell909090 从你角度考虑，通过zk实现influx-proxy的高可用负载，怎么样？

**Comment by shell909090** [comment]
从我的角度，我不理解为啥已经被实现过无数次的LB问题还要讨论怎么用zk实现...
