### ISSUE TITLE
您好，请问代理分发给两台influxdb服务器，但数据结构中有一个始终多一个字段

### ISSUE THREAD

**Issue by zouxuchao** [shell909090/influx-proxy#95]
1、第一个台数据库插入的格式：
多了一个internal1 
> select * from "temperature"
name: temperature
time                                                    external internal internal1 machine type
----                                                         -------- -------- --------- ------- ----
2015-06-11T20:46:02.000000035Z 100      32                              unit42  assembly
2015-06-11T20:46:02.005000035Z 130      22                              unit42  assembly
2015-06-11T20:46:02.006000035Z 130      23332                        unit42  assembly

2、第二个台数据库插入的格式：
> select * from "temperature"
name: temperature
time                                               external internal machine type
----                                                 -------- -------- ------- ----
2015-06-11T20:46:02.000000035Z 100      32          unit42  assembly
2015-06-11T20:46:02.005000035Z 130      22          unit42  assembly
2015-06-11T20:46:02.006000035Z 130      23332    unit42  assembly

为啥 第一个比第二多了一个字段哈

**Comment by shell909090** [comment]
没看出来啊。你是不是贴了两次第二台机器的样本？
还有，你的原始插入样本有么？

**Comment by zouxuchao** [comment]
第一台：





第二台：

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shell.Xu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 晚上8:25
收件人:&nbsp;"shell909090/influx-proxy"<influx-proxy@noreply.github.com&gt;;
抄送:&nbsp;"超人"<544462382@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [shell909090/influx-proxy] 您好，请问代理分发给两台influxdb服务器，但数据结构中有一个始终多一个字段 (#95)




没看出来啊。你是不是贴了两次第二台机器的样本？
 还有，你的原始插入样本有么？

**Comment by zouxuchao** [comment]
这个回复中没发展示，邮件中可以展示，插入脚本也有，帮忙看一下

**Comment by shell909090** [comment]
我这里什么都看不到啊...
这么说吧。influx-proxy并不负责每条内容的检查，它只是机械的检查这个内容归哪个后端管，然后原封发送给后端。所以我希望检查这么几个内容。

1. 写入请求的样子，是不是多一个column。
2. 后端写入的内容，同理。
3. 后端返回的内容，同理。

如果我们认为这个column是“多出来的”，那么最起码得知道是哪个环节多出来的。

**Comment by zouxuchao** [comment]
通过邮件可以看到 ，githup不支持图片。。
1、插入脚本如下
from __future__ import absolute_import, division,\
    print_function, unicode_literals
import time
import requests

BASEURL = 'http://localhost:6666'

def once():
    s = '''cpu,host=server01,region=uswest value=1 1434055562000000000
cpu value=3,value2=4 1434055562000010000
temperature,machine=unit42,type=assembly internal=32,external=100 1434055562000000035
temperature,machine=unit42,type=assembly internal=22,external=130 1434055562005000035
temperature,machine=unit42,type=assembly internal=23332,external=130 1434055562006000035'''
    resp = requests.post(
        BASEURL+'/write', params={'db': 'zxcdb'}, data=s)
    print(resp.status_code)

def main():
    while True:
        once()
        time.sleep(0.1)

if __name__ == '__main__':
    main()

2、使用代理插入的，中间没有任何更改，第一个数据库出入中多了一个字段internal1，但没有时间值 ，第二个没有internal1字段
第一个字段：time external internal internal1 machine type
第二个字段：time external internal                machine type

这个问题很奇怪 。

**Comment by zouxuchao** [comment]
![微信截图_20191120210851](https://user-images.githubusercontent.com/49740758/69241546-0271a600-0bda-11ea-9b67-5d7b1263b956.png)
![微信截图_20191120210940](https://user-images.githubusercontent.com/49740758/69241618-1ae1c080-0bda-11ea-8ffd-57a70c932c13.png)

**Comment by zouxuchao** [comment]
1、原来是规划3个服务
代理是：A服务器
influxDB1：B服务器【local】
influxDB2：C服务器【local2】
influxDB1服务器插入任何表，都会在数据库中多一个字段，

2、现在influxDB1换做A服务器，和代理是一个服务器插入正常

**Comment by shell909090** [comment]
所以问题是influxdb1会多一个column...多谢。
不过还是不知道为什么influxdb1会多一个column。

**Comment by zouxuchao** [comment]
是的，还是没有找到原因，但是切换了就是ok的。


大神还方便加个微信哈：zouxuchao001


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shell.Xu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 晚上11:42
收件人:&nbsp;"shell909090/influx-proxy"<influx-proxy@noreply.github.com&gt;;
抄送:&nbsp;"超人"<544462382@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [shell909090/influx-proxy] 您好，请问代理分发给两台influxdb服务器，但数据结构中有一个始终多一个字段 (#95)




所以问题是influxdb1会多一个column...多谢。
 不过还是不知道为什么influxdb1会多一个column。
