### ISSUE TITLE
您好，这个问题是关于query的

### ISSUE THREAD

**Issue by imade1994** [shell909090/influx-proxy#96]
[root@localhost ~]# curl -G 'http://127.0.0.1:8086/query?pretty=true' --data-urlencode "db=myinfluxdb" --data-urlencode "q=select * from \"hlxd\" where \"region\"='china'"
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "hlxd",
                    "columns": [
                        "time",
                        "host",
                        "name1",
                        "region",
                        "value"
                    ],
                    "values": [
                        [
                            "2019-12-03T06:25:30.086865252Z",
                            "server0003",
                            null,
                            "china",
                            0.88
                        ]
                    ]
                }
            ]
        }
    ]
}
[root@localhost ~]# curl -G 'http://127.0.0.1:6666/query?pretty=true' --data-urlencode "db=myinfluxdb" --data-urlencode "q=select * from \"hlxd\" where \"region\"='china'"
query forbidden[root@localhost ~]# 
我请求8086端口查询是正常的，但是请求6666端口查询就报400

**Comment by shell909090** [comment]
这是个说明不清的坑。
https://github.com/shell909090/influx-proxy/blob/master/backend/commands.go
代码里禁止了一些耗时巨大的查询语句。你干掉这些限制重新启动proxy，问题应该就可以消失。
