### ISSUE TITLE
为什么要用Redis来存配置信息,用属性文件不好吗

### ISSUE THREAD

**Issue by www6223166** [shell909090/influx-proxy#97]
您好,最近自信拜读了您的源码,有一点一直有疑惑,配置信息通过Python读取到Redis中,Proxy在启动的时候加载了一次以后,就再也没用到了.是什么原因决定使用Redis呢,个人觉得一个配置文件就能解决呀,求大神解答

**Comment by shell909090** [comment]
因为早年本来是打算第二期改用etcd的。后来...就没有后来了。

**Comment by www6223166** [comment]
好吧,我尝试着改成属性文件的方式o(∩_∩)o

**Comment by shell909090** [comment]
多谢。
这里有两点可能对你有用的。一个是在这个文件中。
https://github.com/shell909090/influx-proxy/blob/master/backend/config.go
你可以多加一个接口，里面三个方法，LoadNode，LoadBackends，LoadMeasurements。这三个都是不和redis实现绑定的。定义了这个接口后，其他文件里就可以直接引用接口，redis就变成了config的一个impl。这是原本预留给etcd的扩充，你可以直接利用起来。
第二个是，建议做http版的config，直接从一个给定URL download一个json文件。然后直接解析这个json文件实现LoadNode，LoadBackends，LoadMeasurements的内容。这个文件就和现在的config.py里的东西对应起来了。

**Comment by www6223166** [comment]
多谢指点,我用的您建议的第二种方法,读取JSon文件并解析,依照原来的数据结构放入LoadNode,LoadBackends,LoadConfigFromRedis,LoadMeasurements方法中解析并返回

**Comment by shell909090** [comment]
我记得LoadConfigFromRedis不对外暴露，不知道有没有记错。

**Comment by www6223166** [comment]
您说的是对的,属性文件这块已经改完了,突然还意识到一个问题,运维要求生产数据库必须设置账号密码,我好像还得改o(︶︿︶)o

**Comment by shell909090** [comment]
我觉得你把用户名/密码放在另一个分支里做比较好，和属性文件这件事正交。
密码比较麻烦之处在于，如果密码放在配置文件里，那么配置文件的访问就需要加密码。你可以试试golang的Get是不是能接受一个形如`https://username:password@host:port/path.json`的URL。如果可以的话，这个问题可以在不增加复杂度的情况下比较好的解决。
