### ISSUE TITLE
influxdb 出现 partial write: max-values-per-tag limit exceeded (100000/100000):

### ISSUE THREAD

**Issue by caiyeyu** [shell909090/influx-proxy#98]
你好,influxdb 出现 partial write: max-values-per-tag limit exceeded (100000/100000):的时候，你们有比较好的处理方案吗？

**Comment by shell909090** [comment]
你是说这个？
https://stackoverflow.com/questions/43770354/max-values-per-tag-limit-exceeded-influxdb

**Comment by caiyeyu** [comment]
是你发的这个，默认设置是max-values-per-tag = 0，当tag数量到10w的时候,还是出现这个错,你们有好的解决方案吗？

**Comment by shell909090** [comment]
改源码重编译算么？
